import type { Metadata } from "next";
import Link from "next/link";
import { ExternalLink, CheckCircle2, ArrowRight } from "lucide-react";

export const metadata: Metadata = {
  title: "Research — RentLens",
  description: "How we found and validated the RentLens micro-SaaS opportunity.",
};

const checklist = [
  { label: "10+ posts with this pain", passed: true },
  { label: "Paying for inferior solution", passed: true },
  { label: "Reachable channel", passed: true },
  { label: "MVP < 4 weeks", passed: true },
  { label: "Price point high enough", passed: true },
  { label: "Hair-on-fire problem", passed: true },
  { label: "Can pre-sell", passed: true },
  { label: "< 3 competitors", passed: true },
  { label: "AI-agent operable", passed: true },
];

const painPoints = [
  {
    problem:
      "Real estate investors struggle to track finances across multiple properties, understand true value per property, and identify which are generating cash flow vs. costing money.",
    persona: "Real estate investor managing multiple properties",
    workaround: "Juggling multiple spreadsheets to track properties and finances",
    frequency: "weekly",
    wtp: "Built custom dashboard (Earn Clarity) to replace spreadsheets",
    source: "https://www.reddit.com/r/SideProject/comments/1unp3zy/got_tired_of_juggling_spreadsheets_to_track_my/",
  },
  {
    problem:
      "Managing multiple spreadsheets for rental properties is tedious and doesn't provide unified visibility into tenants, maintenance, rent tracking, and financial performance.",
    persona: "Landlord managing multiple rental properties",
    workaround: "Managing multiple spreadsheets or ditching property management apps entirely",
    frequency: "weekly",
    wtp: "Built custom Notion system to consolidate property management",
    source: "https://www.reddit.com/r/Notion/comments/1ue3u6b/built_a_notion_system_to_manage_my_rental/",
  },
];

export default function ResearchPage() {
  return (
    <div className="bg-surface-900">
      <div className="border-b border-white/10 bg-surface-800/50">
        <div className="mx-auto max-w-3xl px-6 py-16">
          <p className="text-sm font-medium text-brand-400">Idea Miner Research</p>
          <h1 className="mt-2 font-display text-4xl font-bold text-white">How we found this idea</h1>
          <p className="mt-4 text-lg text-slate-400">
            Unified AI dashboard turns scattered landlord spreadsheets into live property P&amp;L
            automatically.
          </p>
        </div>
      </div>

      <article className="mx-auto max-w-3xl px-6 py-12 prose-sections">
        {/* Why this research program exists */}
        <section className="mb-12">
          <h2 className="font-display text-2xl font-bold text-white">Why this research program exists</h2>
          <p className="mt-4 leading-relaxed text-slate-400">
            This app was auto-generated by the <strong className="text-slate-300">Idea Miner</strong> pipeline — a
            twice-daily research program that hunts for validated micro-SaaS opportunities from real people
            expressing real pain online (Reddit, Hacker News, Stack Exchange, GitHub, and more).
          </p>

          <h3 className="mt-8 text-lg font-semibold text-white">What we&apos;re looking for</h3>
          <ul className="mt-4 space-y-3">
            {[
              "Self-running micro-SaaS — one specific problem, a small dedicated user base, minimal manual ops (digital-nomad friendly).",
              "AI-agent operable — daily support, content, and processing handled by autonomous agents on self-hosted LLMs (not locked into expensive cloud API token bills).",
              "Real pain only — every idea must trace back to actual posts where people complain, ask \"is there a tool for X?\", or say \"I wish someone would build…\".",
              "B2B & recurring revenue preferred — higher willingness to pay, lower churn.",
              "Markets with <3 established competitors — room for a focused wedge.",
              "MVP in under 4 weeks — solo-dev buildable, no regulatory/hardware/capital barriers.",
            ].map((item) => (
              <li key={item} className="flex gap-3 text-sm text-slate-400">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-brand-400" />
                {item}
              </li>
            ))}
          </ul>
        </section>

        {/* Why this demo was built */}
        <section className="mb-12">
          <h2 className="font-display text-2xl font-bold text-white">Why this demo was built</h2>
          <p className="mt-4 leading-relaxed text-slate-400">
            When an idea passes the validation gate (≥8/9 checklist items, not declining on Google Trends,
            not previously built), the pipeline automatically ships a working mock on Vercel so we can see
            the product story, not just a slide deck.
          </p>
        </section>

        {/* This specific idea */}
        <section className="mb-12">
          <h2 className="font-display text-2xl font-bold text-white">This specific idea</h2>
          <div className="mt-6 grid gap-4 sm:grid-cols-2">
            <div className="rounded-xl border border-white/10 bg-surface-800 p-4">
              <p className="text-xs text-slate-500">Weighted Score</p>
              <p className="font-display text-3xl font-bold text-brand-400">114/130</p>
            </div>
            <div className="rounded-xl border border-white/10 bg-surface-800 p-4">
              <p className="text-xs text-slate-500">Validation</p>
              <p className="font-display text-3xl font-bold text-brand-400">9/9</p>
            </div>
          </div>
          <p className="mt-4 text-sm text-slate-400">
            <strong className="text-slate-300">Cluster:</strong> Rental Property Financial Tracking
          </p>
          <p className="mt-2 text-sm text-slate-400">
            <strong className="text-slate-300">Why we built this demo:</strong> AI-generated plain-English
            monthly narrative report is a unique deliverable no spreadsheet or existing tool produces;
            self-hosted LLM makes report generation near-zero marginal cost.
          </p>
        </section>

        {/* Product specification */}
        <section className="mb-12">
          <h2 className="font-display text-2xl font-bold text-white">Product specification</h2>
          <p className="mt-4 text-sm text-slate-400">
            <strong className="text-slate-300">Target customer:</strong> Independent landlords and small
            real estate investors managing 2–20 rental properties
          </p>

          <h3 className="mt-6 text-lg font-semibold text-white">Core MVP features</h3>
          <ul className="mt-3 space-y-2">
            {[
              "CSV/spreadsheet import wizard plus bank feed connection to auto-categorize income and expenses per property",
              "Per-property P&L, cash-on-cash return, and vacancy rate calculated automatically each month",
              "Tenant ledger: rent due, paid, overdue with automated reminder SMS/email drafts",
              "Maintenance log linked to expense records so repair costs appear in property P&L",
              "AI-generated monthly owner report PDF summarizing portfolio health and flagging underperforming properties",
            ].map((f) => (
              <li key={f} className="flex gap-3 text-sm text-slate-400">
                <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-brand-400" />
                {f}
              </li>
            ))}
          </ul>

          <div className="mt-6 space-y-3 text-sm text-slate-400">
            <p><strong className="text-slate-300">Pricing:</strong> $29/mo (up to 5 properties), $59/mo (up to 20 properties), $99/mo (unlimited)</p>
            <p><strong className="text-slate-300">Go-to-market:</strong> Reddit r/realestateinvesting, r/landlord, BiggerPockets forums, YouTube ads targeting &apos;rental property spreadsheet&apos; searches</p>
            <p><strong className="text-slate-300">Competitive landscape:</strong> Stessa is free but limited on analytics depth; Buildium and AppFolio are enterprise-priced and complex; no AI-narrative reporting tool in this niche</p>
            <p><strong className="text-slate-300">Agentic automation:</strong> Agent runs on 1st of each month: pulls transactions, categorizes via fine-tuned classifier, computes per-property KPIs, generates PDF report, emails to landlord — zero manual steps after initial setup</p>
            <p><strong className="text-slate-300">MVP estimate:</strong> Next.js + Supabase + Plaid for bank feeds + self-hosted LLaMA for report generation; 3–4 weeks for MVP with CSV import and manual bank entry before Plaid integration</p>
          </div>
        </section>

        {/* Validation checklist */}
        <section className="mb-12">
          <h2 className="font-display text-2xl font-bold text-white">Validation checklist (9/9)</h2>
          <div className="mt-6 grid gap-2 sm:grid-cols-2">
            {checklist.map((item) => (
              <div key={item.label} className="flex items-center gap-2 rounded-lg border border-white/10 bg-surface-800 px-4 py-3">
                <CheckCircle2 className="h-4 w-4 text-brand-400" />
                <span className="text-sm text-slate-300">{item.label}</span>
              </div>
            ))}
          </div>
        </section>

        {/* Source pain points */}
        <section className="mb-12">
          <h2 className="font-display text-2xl font-bold text-white">Source pain points (real posts)</h2>
          <div className="mt-6 space-y-6">
            {painPoints.map((pp) => (
              <div key={pp.source} className="rounded-xl border border-white/10 bg-surface-800 p-6">
                <p className="text-sm leading-relaxed text-slate-300">{pp.problem}</p>
                <dl className="mt-4 grid gap-2 text-xs sm:grid-cols-2">
                  <div><dt className="text-slate-500">Persona</dt><dd className="text-slate-400">{pp.persona}</dd></div>
                  <div><dt className="text-slate-500">Workaround</dt><dd className="text-slate-400">{pp.workaround}</dd></div>
                  <div><dt className="text-slate-500">Frequency</dt><dd className="text-slate-400">{pp.frequency}</dd></div>
                  <div><dt className="text-slate-500">WTP signal</dt><dd className="text-slate-400">{pp.wtp}</dd></div>
                </dl>
                <a
                  href={pp.source}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="mt-4 inline-flex items-center gap-1 text-sm text-brand-400 hover:underline"
                >
                  View source post <ExternalLink className="h-3 w-3" />
                </a>
              </div>
            ))}
          </div>
        </section>

        <p className="text-xs text-slate-500">
          Generated by Idea Miner run 2026-07-10-pm on 2026-07-10 20:34 UTC
        </p>

        <div className="mt-12 text-center">
          <Link
            href="/demo"
            className="inline-flex items-center gap-2 rounded-lg bg-brand-500 px-6 py-3 text-sm font-semibold text-white hover:bg-brand-600"
          >
            Explore the Interactive Demo <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </article>
    </div>
  );
}
